### ISSUE TITLE
TODO for release 6

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo#10112]
- [x] disable build process in deployment
- [x] remove travis actions in framework
- [x] remove deploy process in framework, api viewer, and anything else
- [x] remove deploy process in compiler 
- [x] create `latest` branch on github
- [x] edit `package.json` on compiler and framework to have the exact version numbers (1.0.0 and 6.0.0, ie remove "-beta" suffix)
- [x] Also edit dependency version numbers, with bumpqxversion.py in latest
- [x] manually trigger deployment to release stable versions on npm (possibly use `npm pack` to dry run the release)
- [x] create a release on github
- [x] set version in documentation
- [x] set version on website
- [x] move all qxl packages to the new version and rebuild them.
- [x] check there has been a successful release / celebrate!
- [x] create 6.0.0 tag on HEAD (which should still be HEAD of both `latest` and `master` at this point), done with release on github
- [x] set `master` version in `package.json` to 7.0.0-beta
- [x] Make sure that all badges in https://qooxdoo.org/status/ and https://github.com/qooxdoo/qooxdoo don't display any broken state for the v6 release
- [x] create a compiler release on github
# when all is done
- [x] Announce on redit/twitter/facebook
- [x] Twitter
- [x] Announce on main list with link to medium story
- [x] Release Medium story

**Comment by johnspackman** [comment]
I've edited the above slightly, changing the order and adding a few extra details

**Comment by hkollmann** [comment]
Should we clean up master branch in this step too?
Delete Apps and Python stuff, move Framework/source to source dir?

**Comment by derrell** [comment]
I add added a `create 6.0.0 tag` step so we have it tagged and don't lose it due to ongoing work

**Comment by cboulanger** [comment]
> Delete Apps and Python stuff, move Framework/source to source dir?

Yes, this would make the framework truly just another source library for compilation. There's no need any more to put the qx core sources in another to-level directory.

**Comment by hkollmann** [comment]
Then we have to fix the compiler too. Function getQxPath

**Comment by cboulanger** [comment]
That's why we need to merge the compiler - so that such changes don't create a headache-inducing intra-repository dependency hell.

**Comment by hkollmann** [comment]
Sorry i just want to write down that as reminder

**Comment by cboulanger** [comment]
Sure! I added the steps in the list above.

**Comment by hkollmann** [comment]
update qxl packages to 6.0.0

- [ ] qxl.apiviewer
- [ ] qxl.datademo
- [ ] qxl.demobrowser
- [ ] qxl.dialog
- [ ] qxl.formdemo
- [ ] qxl.iconfontviewer
- [ ] qxl.logpane
- [ ] qxl.mobileshowcase
- [ ] qxl.packagebrowser
- [ ] qxl.playground
- [ ] qxl.testnode
- [ ] qxl.testrunner
- [ ] qxl.testtapper
- [ ] qxl.tutorial
- [ ] qxl.tweet-tutorial
- [ ] qxl.versionlabel
- [ ] qxl.widgetbrowser

**Comment by hkollmann** [comment]
all is done. Can be closed
