### ISSUE TITLE
TODO Post-v6-release

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo#10117]
More complicated items or those requiring a discussion should have their individual issue, to which we link here:

- [x] Make sure that all badges in https://qooxdoo.org/status/ and https://github.com/qooxdoo/qooxdoo don't display any broken state for master, disable until everything works again
- [x] remove all generator-related directories (application, component, tool)
- [x]  merge https://github.com/qooxdoo/qooxdoo/pull/10104
- [x] move `framework/source` to `source` 
- [x] fix tests
- [x] fix qx lint issues
- [x] merge compiler into framework 
    - [x] update config & compiler `getQxPath()`
    - [x] move open issues from qooxdoo/qooxdoo-compiler/issues to qooxdo/qooxdoo/issues 
    - [x] update `qx package migrate` to update `"$schema": "https://github.com/qooxdoo/qooxdoo-compiler/XXX/YYY.json",` `"$schema": "https://qooxdoo.org/schema/YYY.json",` in the configuration files
- [ ] archive the https://github.com/qooxdoo/deployment script
- [x] update https://github.com/qooxdoo/qooxdoo-compiler to reflect new base in framework repo
- [x] adapt the existing deployment script to run testing of merged framework & compiler
- [x] re-integrate documentation, so that it can be versioned and PR can contain changes to both code and documentation at the same time
- [ ] Create infrastructure for automating tasks:
    - [ ] Create bot user which we can use to automate tasks which don't need to be attributed to one of the team members, see https://stackoverflow.com/questions/29177623/what-is-a-bot-account-on-github
    - [ ] have a look whether https://github.com/probot/probot can be useful 
- [x] https://github.com/qooxdoo/documentation/issues/24 : create workflow that publishes documentation from qooxdoo/qooxdoo in qooxdoo/documentation in a versioned form (i.e. qooxdoo.org/documentation/6.0/ ... qooxdoo.org/documentation/7.1/, etc.
- [ ]  https://github.com/qooxdoo/qooxdoo/issues/10109 : find a consensus on the exact form of semantic-release (see and long gitter discussion) by providing an implementation PR that can be discussed:
    - [ ] add semantic-release script to the new deployment script
    - [x] edit deployment script to release the version in `package.json` (ie do not automatically update version numbers)
    - [ ] adapt PR workflow to only accept semantic-release-conformant commit messages 
    - [ ] adapt PR workflow to only accept breaking and feature PRs that also provide documentation. This could be extended to create a PR comment strongly suggesting to add a demo in the demobrowser for feature PRs, so that they won't be forgotten.
    - [ ] configure `.releaserc` (for semver-release)
- [x] reset pullaprove 

**long term**
- [x] delete deprecated methods
- [ ] rework lint exceptions

**Comment by hkollmann** [comment]
Are we shure that we want to  move open issues from qooxdoo/qooxdoo-compiler/issues to qooxdo/qooxdoo/issues?
IMHO the compiler repos should be stay there to build the compiler.
Or should we move the build process to?
@johnspackman what do you think?

**Comment by johnspackman** [comment]
open issues should move but closed ones can stay so that the todo list is all in one place.  

I was thinking that the qooxdoo-compiler repo would be archived and all the code would move into framework; and that the release workflow in framework would bootstrap the compiler and release; was that not what you were thinking?

**Comment by hkollmann** [comment]
That's ok for. Should be your task then.
IMHO we should have a compiler subdir for all the compiler bootstrap stuff then.

**Comment by hkollmann** [comment]
Only 17 tests left to fix:
TESTTAPPER: Running test in chromium
not ok 837 - qx.test.ui.toolbar.OverflowHandling:testShowItemRemoved - Event (showItem) not fired.
not ok 1209 - qx.test.Mixin:testPatchOverwritten - Cannot find base class method called sayJuhu for mixin qx.MPatch, when viewed from qx.Patch1
not ok 1694 - qx.test.bom.rest.Resource:test: invoke action ignores invalid check in production - Expected value to be a regular expression but found !
not ok 1723 - qx.test.bom.rest.Resource:test: dispose request on loadEnd - resume() called before wait()
not ok 1725 - qx.test.bom.rest.Resource:test: fire started - Timeout of 500 ms reached before resume() was called.
not ok 1726 - qx.test.bom.rest.ResourceWithRemote:test: poll action - Timeout of 10000 ms reached before resume() was called.
not ok 1730 - qx.test.bom.rest.ResourceWithRemote:test: long poll - Called assert with 'false'
not ok 1952 - qx.test.io.rest.Resource:test: invoke action ignores invalid check in production - Expected value to be a regular expression but found !
not ok 1980 - qx.test.io.rest.ResourceWithRemote:test: invoke action and handle response - Timeout of 10000 ms reached before resume() was called.
not ok 1982 - qx.test.io.rest.ResourceWithRemote:test: poll action - resume() called before wait()
not ok 2093 - qx.test.io.rest.ResourceWithRemote:test: invoke action and handle failure - Timeout of 10000 ms reached before resume() was called.
not ok 2522 - qx.test.dev.StackTrace:testFilenameConverterDefault - The String 'http://localhost:8080/testtapper/package-191.js:2603:29' does not match the regular expression '/((?:test\.dev\.StackTrace)|(?:dev\.unit)|(?:qxl\.testrunner)|(?:testrunner\.js)|(?:tests\.js)|(?:qooxdoo-adapter\.js))/'!
not ok 2774 - qx.test.lang.normalize.Date:test parse() - Expected '-377736727708000' (identical) but found '-377736728100000'!
not ok 2788 - qx.test.locale.Locale:testMacCtrl - Expected 'Links' but found 'Left'!
not ok 3179 - qx.test.util.DateFormat:testChangingLocales - Expected 'lundi 2021-39-08' but found 'Monday 2021-39-08'!
not ok 3190 - qx.test.util.Function:testDebounce - Called fail().
not ok 3192 - qx.test.util.Function:testImmediateDebounce - Called fail().
DONE testing 3303 ok, 17 not ok

Could someone help out?

**Comment by hkollmann** [comment]
Only 7 test have to be fixed.

not ok 837 - qx.test.ui.toolbar.OverflowHandling:testShowItemRemoved - [16.97 ms] - Event (showItem) not fired.
not ok 1209 - qx.test.Mixin:testPatchOverwritten - [0.60 ms] - Cannot find base class method called sayJuhu for mixin qx.MPatch, when viewed from qx.Patch1
not ok 1694 - qx.test.bom.rest.Resource:test: invoke action ignores invalid check in production - [14.46 ms] - Expected value to be a regular expression but found !
not ok 1722 - qx.test.bom.rest.Resource:test: dispose request on loadEnd - [32.86 ms] - resume() called before wait()
not ok 1730 - qx.test.bom.rest.Resource:test: fire started - [0.81 ms] - Timeout of 500 ms reached before resume() was called.
not ok 1952 - qx.test.io.rest.Resource:test: invoke action ignores invalid check in production - [18.60 ms] - Expected value to be a regular expression but found !
not ok 2773 - qx.test.lang.normalize.Date:test parse() - [12.79 ms] - Expected '-377736727708000' (identical) but found '-377736728100000'!
DONE testing 3226 ok, 7 not ok, 172 skipped - [324119 ms]

Could someone help out?

**Comment by derrell** [comment]
@johnspackman Maybe you can look at test
```
not ok 1209 - qx.test.Mixin:testPatchOverwritten - [0.60 ms] - Cannot find base class method called sayJuhu for mixin qx.MPatch, when viewed from qx.Patch1
```

based on the following simpler test:

```
qx.Class.define("kludge.Application",
{
  extend : qx.application.Basic,

  members :
  {
    main : function()
    {
      qx.Class.patch(kludge.Patch1, kludge.MPatch);

      var o = new kludge.Patch1();
      this.assertEquals("Juhu Kinners", o.sayJuhu());
      o.dispose();
    }
  }
});
```

```
qx.Class.define("kludge.Patch1", 
{
  extend : qx.core.Object,

  members : {
    sayJuhu : function()
    {
      return "Juhu";
    }
  }
});
```

```
qx.Mixin.define("kludge.MPatch",
{
  members :
  {
    sayJuhu : function()
    {
      return this.base(arguments) + " Kinners";
    }
  }
});
```

Running this (without the test framework) invokes the problem. Tracing into `Mixin.js`, in `baseClassMethod`, I get this:

```
mixedInAt.$$flatIncludes= [
  {
    "$$members": {},
    "$$type": "Mixin",
    "name": "kludge.MPatch",
    "basename": "MPatch",
    "$$dbClassInfo": {
      "dependsOn": {
        "qx.Mixin": {
          "usage": "dynamic",
          "require": true
        }
      }
    }
  }
]
```

`$$members` is an empty map and there is no `superclass` member. Therefore, no base class method is found.

**Comment by derrell** [comment]
For test 

```
not ok 1694 - qx.test.bom.rest.Resource:test: invoke action ignores invalid check in production - [14.46 ms] - Expected value to be a regular expression but found !
```
the problem is that the `stub` function is not working properly. Adding a debug statement immediately after creating the stub, as shown here at `qx/test/bom/rest/Resource.js:518`, tells us that `qx.debug` is true even though the stub should have made it false. I'm not sure how these stubs work. (I also confirmed that `qx.debug` is true in `__checkParameters` called via `res.map`. If anyone is well familiar with them, maybe you can figure out why the stub is failing to return false.

```
      var setting = this.stub(qx.core.Environment, "get").withArgs("qx.debug");
      setting.returns(false);
      console.log("In test, qx.debug=", qx.core.Environment.get("qx.debug")); // incorrectly returns true
```

**Comment by hkollmann** [comment]
The problem here is that qx.debug is evaluated to compile time. So stub can not work: 
See transpiled Resource class:
```
  __checkParameters: function __checkParameters(params, check) {
        if (typeof check !== "undefined") {
          {
            qx.core.Assert.assertObject(check, "Check must be object with params as keys");
          }
          Object.keys(check).forEach(function (param) {
            // Warn about invalid check
            {
              if (check[param] !== true) {
                {
                  qx.core.Assert.assertRegExp(check[param]);
                }
              }
            } // Missing parameter

            if (check[param] === qx.bom.rest.Resource.REQUIRED && typeof params[param] === "undefined") {
              throw new Error("Missing parameter '" + param + "'");
            } // Ignore invalid checks


            if (!(check[param] && typeof check[param].test == "function")) {
              return;
            } // Invalid parameter


            if (!check[param].test(params[param])) {
              throw new Error("Parameter '" + param + "' is invalid");
            }
          });
        }
      },
```

**Comment by derrell** [comment]
Compiling code out, based on `qx.debug`, is a good thing. That's particularly true with compiling engine-specific code in or out when requested. I wonder, though, if for testing purposes, we ought to have a compiler flag that tells it not to compile the code out; rather, to make the determination at run-time instead?

**Comment by hkollmann** [comment]
Setting "qx.debug": false in compile.json did the work.

**Comment by derrell** [comment]
Ah, but that affects *all* tests, rather than just this one, right? It's probably good that we test with qx.debug turned off, but tests for things that don't work with it turned off now wont work, e.g., tests for `check` in properties...

**Comment by hkollmann** [comment]
Good idea - should be an issue.

**Comment by hkollmann** [comment]
with https://github.com/qooxdoo/qooxdoo/pull/10139 only 2 errors left:

**Comment by johnspackman** [comment]
> @johnspackman Maybe you can look at test
> not ok 1209 - qx.test.Mixin:testPatchOverwritten - [0.60 ms] - Cannot find base class method called sayJuhu for mixin qx.MPatch, when viewed from qx.Patch1

No problem

> I wonder, though, if for testing purposes, we ought to have a compiler flag that tells it not to compile the code out; rather, to make the determination at run-time instead?

That code elimination only happens if the environment variable applies to all applications, so if in `compile.json` you define `target.environment["qx.debug"]` to be "foo", and one application's `environment["qx.debug"]` is `true` and the other is `false`, then code to `qx.core.Environment.get("qx.debug")` will always be done at runtime.

I think that you can also fool the compiler by using variables, eg `let str = "qx.debug"; if (qx.core.Environment.get(str)) {...}`, but AIACR it will figure literals out, so that `qx.core.Environment("qx" + "." + "debug")` will not help you

**Comment by hkollmann** [comment]
I will try this

Von meinem iPhone gesendet

**Comment by hkollmann** [comment]
On the way to v7
