### ISSUE TITLE
TODO for release V7

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo#10342]
Let's release a new version! This has to be done:

- [x] adjust https://github.com/qooxdoo/qooxdoo/blob/master/docs/history.md
- [ ] copy apiviewer doc from latest to v6.0.
- [x]  write new https://github.com/qooxdoo/qooxdoo/blob/master/docs/release-notes.md
- [x] adjust https://github.com/qooxdoo/qooxdoo/blob/master/docs/roadmap.md
- [x] write a new news entry https://news.qooxdoo.org/

**Comment by johnspackman** [comment]
WRT to the roadmap, I have a couple of thoughts / plans:

**Properties**: this is mentioned in the roadmap already, my plan is (I've already started) to completely rewrite the property system so that it is not based on code generation and to add features like:

- Native properties (`myObj[0]` instead of `getMyObj().getItem(0)`);
- Allow for getters & setters to be completely redefined, eliminating the need for psuedo-properties to be created by hand;
- Weak, Soft, and On-Demand references, with automatic garbage collection of objects that can include destructor and other hooks;
- Better type checking in properties and arrays, with support for parameterised types;
- Add a `qx.data.Map` that works like `qx.data.Array` and add type checking to `qx.data.Array` and `qx.data.Map`;
- Private & protected properties, allowing for member variables to be implemented as properties so that they benefit from type checking and reference support;
- Immutable and set-once properties

**Remote and persistence incubators**: these are quite a bit out of date, and IMHO much easier to understand and use if integrated together, and ideally as part of a server framework.  My current version is a lot further along than these, but I'm holding off because of the work involved in making that first release with documentation

**JSDOC**: update the codebase to correct the JSDOC usage

### Roadmap v9
Proposed features for this could include 

**Type Checking** - add automatic type checking based on JSDOC - for example, if a method declares that it has `@param {Integer} myInt` then the compiler can add a type check at the start of the function

**Virtual Framework** - Ive spend a lot of time working on the current virtual framework in `qx.ui.virtual` and `qx.ui.list` and I am probably going to withdraw the PR in https://github.com/qooxdoo/qooxdoo/pull/10202 because IMHO it needs so much restructuring it will end up as a new component but also restricted by a lot of the old design decisions.  I propose that `qx.ui.virtual`, `qx.ui.list`, and `qx.ui.treevirtual` are moved into a separate package in preparation for being deprecated, and then we look to building a completely new framework, based on the Soft & On-Demand references in v8.

**Server framework** - ideally this would be in v8, not v9, but pressures of time etc.  Server framework would bring together persistence, network, CMS, a control panel Desktop app, CLI, authentication, plugin support, Nunjucks rendering with themes, a replacement for `qxWeb` for very lightweight HTML UI (currently called "Thin Client"), and automatically memory managed synchronisation of objects between clients and server.  A lot of this is done already.

**qxWeb** Remove qxWeb, which means having an alternative (see server framework and Thin Client)

### Other considerations
**Modularisation**: the Qooxdoo framework is part "core" functionality that applies to all platforms, plus modules for Mobile, Desktop, and Node; adding a server framework would add to the namespace, I'd like to discuss whether we could modularise the codebase

**Comment by cboulanger** [comment]
@johnspackman This is seriously cool stuff!

**Comment by derrell** [comment]
:+1: 

My only concern is deprecation of qx.ui.treevirtual which is based on qx.ui.table and has been around since near the beginning of time. There are likely a large number of projects making use of it. We've talked about writing a Table replacement, but even with that replacement, I don't think we can deprecate the existing qx.ui.table. Similarly, qx.ui.treevirtual. I probably wouldn't be opposed to moving them into installable packages once we have a replacement for them as we did with the recent transport package, although I'd need to think through the consequences such as maintenance.

**Comment by johnspackman** [comment]
> My only concern is deprecation of qx.ui.treevirtual which is based on qx.ui.table

Fair comment.  I can't see `qx.ui.table` being deprecated any time soon either, I'd assumed that `qx.ui.treevirtual` was based on `qx.ui.virtual`.

FWIW the changes that I was [attempting] to make to qx.ui.list etc was to add multiple columns with meta etc; I have previously written a tree-with-columns, and although I've shared that I do not consider it suitable for general publication (it's reliable, but too complicated to use and not as slick as it should be).

(again FWIW) I guess where I'm going with this is that trees, tables, and lists seem to be all sides of the same UI coin; virtual-ness is an independent layer that would be underneath all of those; and that, one day, before I'm completely grey, maybe there will be one set of components for all of it - and in the mean time, let's start to highlight that some of this mixed bag of functionality has some gotchas and focus on a replacement

**Comment by hkollmann** [comment]
Release is done
