### ISSUE TITLE
Documention rework

### ISSUE THREAD

**Issue by hkollmann** [qooxdoo/qooxdoo#9773]
Things to do:

- [x] Fill CR from @derrell in #9770, docs/core/oo_feature_summary.md  
- [x] Fill CR from @derrell in #9770, docs/ebnf_like.md
- [x] Look into docs/_to_be_done/development what's usable
- [x] Look into documentation/manual/source/pages/introduction what's usable, e.g. third party components 
- [x] Same for documentation\manual\source\pages\tool\translation 
- [x] Rework mobile doc
- [x] #9435 Documentint Promise return value (postponed for next release)
- [x] #9019 Karma documentation 
- [x] #9832 List of Environment variables in core (postponed for next release)
- [x] #9825 Optimize docsify navigation bar
- [x] Source code documentation:  (JSDoc/compiler hints) - update and integrate, how to use the apiviewer to generate documentation 
- [x] Link annotations
- [x] Create new section "Core/Non-OO-related features" (of course, find some better title), -> moved into its own issue for later https://github.com/qooxdoo/documentation/issues/1
- [x] Add objectId docs @johnspackman , moved to https://github.com/qooxdoo/documentation/issues/9

**Comment by cboulanger** [comment]
Here's a list of pages as a Todo-List, taken from the sidebar. The list is not complete as the sidebar is manually maintained. We can tick off the pages which we know are updated. This might give us a better motivation to work on this!

- Overview
  - [ ] [Contents](https://github.com/qooxdoo/qooxdoo/tree/master/docs/contents.md)
  - [ ] [Getting Started](https://github.com/qooxdoo/qooxdoo/tree/master/docs/?id=getting-started)
  - [ ] [Qooxdoo Apps](https://github.com/qooxdoo/qooxdoo/tree/master/docs/apps.md)
  - [ ] [About](https://github.com/qooxdoo/qooxdoo/tree/master/docs/about.md)

- Qooxdoo Core
  - [ ] [Overview](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/)
  - [ ] [Introduction into OO](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/oo_introduction.md)
  - [ ] [Feature summary](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/oo_feature_summary.md)

  - Object Orientation
    - [ ] [Classes](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/classes.md)
    - [ ] [Interfaces](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/interfaces.md)
    - [ ] [Mixins](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/mixins.md)
    - [ ] [Annotations](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/annotations.md)
    - [ ] [Arrays](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/array.md)
    - [ ] [Data binding](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/data_binding/)
    - [ ] [Promises](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/promises.md)
    - Class system quickrefs:
        - [ ] [Classes](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/class_quickref.md)
        - [ ] [Interfaces](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/interface_quickref.md)
        - [ ] [Mixins](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/mixin_quickref.md)

  - Properties
    - [ ] [Overview](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/understanding_properties.md)
    - [ ] [Defining properties](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/defining_properties.md)
    - [ ] [Behavior](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/property_behavior.md)
    - [ ] [Features](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/property_features.md)
    - [ ] [Property Quickref](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/properties_quickref.md)

  - Environment
    - [ ] [Overview](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/environment.md)

  - Interaction Events
    - [ ] [Pointer](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/pointer.md)
    - [ ] [Gestures](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/gestures.md)


- Qooxdoo for Desktop

  - Qooxdoo UI
    - [ ] [Interaction](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/interaction.md)
    - [ ] [Resources](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/resources.md)
    - [ ] [Selection](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/selection.md)
    - [ ] [Drag'n'Drop](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/dragdrop.md)
    - [ ] [Forms](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/forms.md)
    - [ ] [Menus](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/menus.md)
    - [ ] [Window Management](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/window_management.md)
    - [ ] [Table Styling](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/table_styling.md)

 - Themes
    - [ ] [Theming](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/theming.md)
    - [ ] [Appearance](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/appearance.md)
    - [ ] [Custom themes](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/themes.md)
    - [ ] [Decorators](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/themes.md#qooxdoo-theme-decorators)

  - Layouts
    - [ ] [Introduction](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/layout/)
    - [ ] [Reference](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/layout/reference.md)
    - [ ] [Alphabetic list](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/layout/layout_list.md)

  - Qooxdoo Widgets
    - [ ] [Introduction](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/widget/)
    - [ ] [Custom widgets](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/customwidgets.md)
    - [ ] [Reference](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/widget/reference.md)
    - [ ] [Alphabetic list](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/widget/widget_list.md)

  - Technical Concepts
    - [ ] [Event layer](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/event_layer_impl.md)
    - [ ] [HTML element handling](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/html.md)
    - [ ] [Focus handling](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/focus.md)

- Qooxdoo for Node
  - [ ] [Introduction](https://github.com/qooxdoo/qooxdoo/tree/master/docs/server/)
  - [ ] [Getting Started](https://github.com/qooxdoo/qooxdoo/tree/master/docs/server/getting_started.md)
  - [ ] [Requirements](https://github.com/qooxdoo/qooxdoo/tree/master/docs/server/requirements.md)

- Qooxdoo Mobile
  - [ ] [Introduction](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/)
  - [ ] [Overview](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/mobile_overview.md)
  - [ ] [Requirements](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/requirements.md)
  - [ ] [Getting Started](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/getting_started.md)
  - [ ] [Debugging](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/debugging.md)
  - [ ] [Deployment](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/deployment.md)
  - [ ] [Mobile and tablet switch](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/mobile_tablet_switch.md)
  - [ ] [Resolution and Pixel Density](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/resolution.md)
  - [ ] [Theming](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/theming.md)

- Communication
  - [ ] [Overview](https://github.com/qooxdoo/qooxdoo/tree/master/docs/communication/)
  - [ ] [REST](https://github.com/qooxdoo/qooxdoo/tree/master/docs/communication/rest.md)
  - [ ] [Remote IO](https://github.com/qooxdoo/qooxdoo/tree/master/docs/communication/remote_io.md)
  - [ ] [Request IO](https://github.com/qooxdoo/qooxdoo/tree/master/docs/communication/request_io.md)
  - [ ] [JSON RPC](https://github.com/qooxdoo/qooxdoo/tree/master/docs/communication/rpc.md)

- Development
  - [ ] [Migrating to the `qx` toolchain](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/migration.md)
  - [ ] ["qx" CLI commands](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/cli/commands.md)
  - [ ] [Package system](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/cli/packages.md)
  - [ ] [Compiler Configuration](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/configuration/overview.md)
    - [ ] [Manifest.json](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/configuration/Manifest.md)
    - [ ] [compile.json](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/configuration/compile.md)
    - [ ] [API](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/configuration/api.md)
  - [ ] [Advanced compiler topics](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/internals/)
  - [ ] [Testing](https://github.com/qooxdoo/qooxdoo/tree/master/docs/development/testing/)
    - [ ] [Unit Testing](https://github.com/qooxdoo/qooxdoo/tree/master/docs/development/testing/unit_testing.md)
    - [ ] [Using qx test](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/cli/testing.md)
    - [ ] [Fake Server](https://github.com/qooxdoo/qooxdoo/tree/master/docs/development/testing/fake_server.md)
    - [ ] [Testing qooxdoo forks](https://github.com/qooxdoo/qooxdoo/tree/master/docs/development/testing/framework_tests.md)

- Deployment (tbd)

- Tutorials

  - Desktop Twitter App
    - [ ] [Introduction](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/)
    - [ ] [1. Getting Started](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-1.md)
    - [ ] [2. Finishing the UI](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-2.md)
    - [ ] [3. Talking to the Server](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-3.md)
    - [ ] [4. Handling Forms](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-4.md)
    - [ ] [5. Creating Custom Widgets](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-5.md)
    - [ ] [6. Theming Widgets](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-6.md)
    - [ ] [7. Translations](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-7.md)
    - [ ] [8. Unit Testing](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-8.md)
    - [ ] [9. Virtual Lists](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-9.md)
  - [ ] [**Qooxdoo Mobile App**](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/tutorial.md)

**Comment by cboulanger** [comment]
Here's a list of pages as a Todo-List, taken from the sidebar. I hope that I managed to assign the tasks roughly by expertise and fairly equally, although it is hard to say how much work the review is in fact. Here are a few things to consider: 

- If you feel like your burden is too high, please say so and I am sure we can redistribute!! We can also exchange or share as we go along. 
- The list is not complete as the sidebar is manually maintained. There might be pages left in the Python/Sphinx/RST docs that haven't been transferred to the MarkDown format, or pages that are not linked in the sidebar. If you feel something is missing, please have a look.
- Most of the old documentation should be up-to-date, but it is important to look through all the pages and replace references to the generator,
- Formatting changes should be done in a separate commit from the substantive changes and be clearly named "Format change", so that comments can be done on the commit containing the substantive change.
    - For example, in order to improve the source code readability (i.e. when you view the MarkDown pages on GitHub), I think it would be good to hard-wrap the text at 80 columns, if your IDE can do this automatically (for example, the JetBrains IDEs have a plugin). 
    - Source code in the RST docs is marked up by indentation. It would be better to have proper GitHub-flavoured MarkDown (i.e. ````javascript ... ) but this is a lot of manual work unless someone comes up with a RegEx to replace it automatically. So we might as well leave it as it is at this point. 
- Style is always a matter of taste, of course, but I as a non-native speaker, I am unsure if the old docs, especially the introductory stuff, are always hitting the right note. Maybe @derrell and @johnspackman can report how they feel about this. On the other hand, revising this might be more work than we can currently afford, and we can postpone the issue. 

We can tick off the pages which we know are updated. 

Please let me know what you think.

- **Overview**
  - [ ] [Contents](https://github.com/qooxdoo/qooxdoo/tree/master/docs/contents.md) - more descriptive text => @cboulanger 
  - [ ] [Getting Started](https://github.com/qooxdoo/qooxdoo/tree/master/docs/?id=getting-started):  Language check => @derrell
  - [x] [Qooxdoo Apps](https://github.com/qooxdoo/qooxdoo/tree/master/docs/apps.md)
  - [ ] [About](https://github.com/qooxdoo/qooxdoo/tree/master/docs/about.md) Language check => @derrell

- **Qooxdoo Core** => @derrell (language & style)
  - [ ] [Overview](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/)
  - [ ] [Introduction into OO](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/oo_introduction.md)
  - [ ] [Feature summary](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/oo_feature_summary.md)

  - **Object Orientation** => @level42
    - [ ] [Classes](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/classes.md)
    - [ ] [Interfaces](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/interfaces.md)
    - [ ] [Mixins](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/mixins.md)
    - [ ] [Annotations](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/annotations.md)
    - [ ] [Arrays](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/array.md)
    - [ ] [Data binding](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/data_binding/)
    - [ ] [Promises](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/promises.md)
    - Class system quickrefs:
        - [ ] [Classes](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/class_quickref.md)
        - [ ] [Interfaces](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/interface_quickref.md)
        - [ ] [Mixins](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/mixin_quickref.md)

  - **Properties** => @level42
    - [ ] [Overview](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/understanding_properties.md)
    - [ ] [Defining properties](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/defining_properties.md)
    - [ ] [Behavior](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/property_behavior.md)
    - [ ] [Features](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/property_features.md)
    - [ ] [Property Quickref](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/properties_quickref.md)

  - **Environment** => @johnspackman
    - [ ] [Overview](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/environment.md)

  - **Interaction Events** => @oetiker
    - [ ] [Pointer](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/pointer.md)
    - [ ] [Gestures](https://github.com/qooxdoo/qooxdoo/tree/master/docs/core/gestures.md)


- Qooxdoo for Desktop 

  - **Qooxdoo UI** => @cboulanger 
    - [ ] [Interaction](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/interaction.md)
    - [ ] [Resources](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/resources.md)
    - [ ] [Selection](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/selection.md)
    - [ ] [Drag'n'Drop](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/dragdrop.md)
    - [ ] [Forms](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/forms.md)
    - [ ] [Menus](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/menus.md)
    - [ ] [Window Management](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/window_management.md)
    - [ ] [Table Styling](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/table_styling.md)

 - **Themes** => @oetiker
    - [ ] [Theming](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/theming.md)
    - [ ] [Appearance](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/appearance.md)
    - [ ] [Custom themes](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/themes.md)
    - [ ] [Decorators](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/themes.md#qooxdoo-theme-decorators)

  - **Layouts** => @level42
    - [ ] [Introduction](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/layout/)
    - [ ] [Reference](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/layout/reference.md)
    - [ ] [Alphabetic list](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/layout/layout_list.md)

  - **Qooxdoo Widgets** => @cboulanger
    - [ ] [Introduction](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/widget/)
    - [ ] [Custom widgets](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/customwidgets.md)
    - [ ] [Reference](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/widget/reference.md)
    - [ ] [Alphabetic list](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/widget/widget_list.md)

  - **Technical Concepts** => @derrell
    - [ ] [Event layer](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/event_layer_impl.md)
    - [ ] [HTML element handling](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/html.md)
    - [ ] [Focus handling](https://github.com/qooxdoo/qooxdoo/tree/master/docs/desktop/gui/focus.md)

- **Qooxdoo for Node** => @johnspackman
  - [ ] [Introduction](https://github.com/qooxdoo/qooxdoo/tree/master/docs/server/)
  - [ ] [Getting Started](https://github.com/qooxdoo/qooxdoo/tree/master/docs/server/getting_started.md)
  - [ ] [Requirements](https://github.com/qooxdoo/qooxdoo/tree/master/docs/server/requirements.md)

- **Qooxdoo Mobile** => @hkollmann
  - [ ] [Introduction](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/)
  - [ ] [Overview](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/mobile_overview.md)
  - [ ] [Requirements](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/requirements.md)
  - [ ] [Getting Started](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/getting_started.md)
  - [ ] [Debugging](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/debugging.md)
  - [ ] [Deployment](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/deployment.md)
  - [ ] [Mobile and tablet switch](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/mobile_tablet_switch.md)
  - [ ] [Resolution and Pixel Density](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/resolution.md)
  - [ ] [Theming](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/theming.md)

- **Communication** => @cboulanger
  - [ ] [Overview](https://github.com/qooxdoo/qooxdoo/tree/master/docs/communication/)
  - [ ] [REST](https://github.com/qooxdoo/qooxdoo/tree/master/docs/communication/rest.md)
  - [ ] [Remote IO](https://github.com/qooxdoo/qooxdoo/tree/master/docs/communication/remote_io.md)
  - [ ] [Request IO](https://github.com/qooxdoo/qooxdoo/tree/master/docs/communication/request_io.md)
  - [ ] [JSON RPC](https://github.com/qooxdoo/qooxdoo/tree/master/docs/communication/rpc.md)

- **Development** => @johnspackman
  - [ ] [Migrating to the `qx` toolchain](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/migration.md)
  - [ ] ["qx" CLI commands](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/cli/commands.md)
  - [ ] [Package system](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/cli/packages.md)
  - [ ] [Compiler Configuration](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/configuration/overview.md)
    - [ ] [Manifest.json](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/configuration/Manifest.md)
    - [ ] [compile.json](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/configuration/compile.md)
    - [ ] [API](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/configuration/api.md)
  - [ ] [Advanced compiler topics](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/internals/)
  - [ ] [**Testing**](https://github.com/qooxdoo/qooxdoo/tree/master/docs/development/testing/) => @oetiker
    - [ ] [Unit Testing](https://github.com/qooxdoo/qooxdoo/tree/master/docs/development/testing/unit_testing.md)
    - [ ] [Using qx test](https://github.com/qooxdoo/qooxdoo/tree/master/docs/compiler/cli/testing.md)
    - [ ] [Fake Server](https://github.com/qooxdoo/qooxdoo/tree/master/docs/development/testing/fake_server.md)
    - [ ] [Testing qooxdoo forks](https://github.com/qooxdoo/qooxdoo/tree/master/docs/development/testing/framework_tests.md)

- **Deployment** (tbd) => @oetiker Anything that could be added here?

- Tutorials => @derrell (language & style check)

  - **Desktop Twitter App** 
    - [ ] [Introduction](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/)
    - [ ] [1. Getting Started](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-1.md)
    - [ ] [2. Finishing the UI](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-2.md)
    - [ ] [3. Talking to the Server](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-3.md)
    - [ ] [4. Handling Forms](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-4.md)
    - [ ] [5. Creating Custom Widgets](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-5.md)
    - [ ] [6. Theming Widgets](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-6.md)
    - [ ] [7. Translations](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-7.md)
    - [ ] [8. Unit Testing](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-8.md)
    - [ ] [9. Virtual Lists](https://github.com/qooxdoo/qooxdoo/tree/master/docs/tutorial/twitter/tutorial-part-9.md)
    
   - [ ] [**Qooxdoo Mobile App Tutorial**](https://github.com/qooxdoo/qooxdoo/tree/master/docs/mobile/tutorial.md)

## Other
- [ ] Release text (for Press release, Medium Blog, etc.) => @oetiker (Draft)
- Release notes
  - [ ] Breaking changes => #9909
  - [ ] Known issues => cold be taken from unresolved bugs

**Comment by derrell** [comment]
"Getting Started" does not seem to exist.

**Comment by cboulanger** [comment]
@hkollmann thanks for working on the docs, I am certainly behind on my homework.

@derrell @johnspackman @level420, have you been able to look at what I suggested you could take over? Is this anything that you'll be able to do in the next couple of weeks?

**Comment by cboulanger** [comment]
I think the most important thing is to look for leftovers of the generator and replace that by references to the compiler docs.

**Comment by derrell** [comment]
I thought I'd gone through what you'd asked me to do, but it looks like there's a lot more. I'll see if I can get through some of it this weekend.

**Comment by cboulanger** [comment]
I think this is almost done, the last remaining step would be to rename the "documentation" folder to "documentation_v5".  I'll create a separate bug. I think this issue can be closed.

**Comment by johnspackman** [comment]
I've made some updates to the docs and ticked off those things with my name on from @cboulanger 's list (some of the links are broken above but they work in the actual docs repo), and it seems that everything else on those lists is done one way or another.
